# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-job:
    name: 'Mobile Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
        
      # ------- Build ---------------
      - name: 'Build'
        run: npm install
        
      # -------------- Test Components ------------------
      # 1.Home
      - name: 'Home Bucket'
        run: npm run website.automation.test
        if: always()
        
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
         channel: test-result
         status: SUCCESS
         color: good
         
      - name: Notify slack fail
        if: failure()
        env:
         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
         channel: test-result
         status: FAILED
         color: danger
